development:
  adapter: postgresql
  encoding: unicode
  database: gistly_development
  pool: 5
  username: tadashi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gistly_test
  pool: 5
  username: tadashi
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gistly_production
  pool: 5
  password:
